* Preface
#+BEGIN_LaTeX
\openepigraph{Emacs is a nice operating system, but what it lacks, in order to compete with Linux, is a good text editor.}{Thomer M. Gil}
#+END_LaTeX

Today, you begin your journey with Emacs, /the extensible, customizable, self-documenting real-time display editor/.

Emacs is complex, and will seem difficult to grok. It takes a certain amount of courage, or an equal amount of frustration, to turn to Emacs. 

This material was originally titled /Hacking Emacs/, because a great deal of customization can and will be made. The tinkerer will marvel at the masterpiece which is Emacs. We hack on it because we can; every facet of Emacs is extensible and customizable.

I have since renamed this piece to "Modern Emacs". Emacs has evolved over several decades, and it is important that our tools are kept up to date. I have handpicked several packages to introduce. These will greatly boost your productivity with the least amount of learning time.

For the novice, this will provide you with a sane environment for you to play around and do some self-exploration. For the first time you'll own your editor: Emacs should designed specifically for your own needs. 

For the intermediate, this presents itself as a literate org-mode configuration. I hope you find something useful in here you could copy.

Atom users, go grab yourselves another cup of coffee while you wait for it to load up :P.
#+BEGIN_LaTeX
\begin{flushright}
#+END_LaTeX
-- Jethro Kuan
#+BEGIN_LaTeX
\end{flushright}
#+END_LaTeX

*** 🢒 [[file:introduction.org][Introduction]]                                                  :noexport:
We begin by introducing Emacs, how to get it, and familiarize ourselves with terminology that will appear again and again in later chapters.
