* Preface
#+BEGIN_LaTeX
\epigraph{Emacs is a nice operating system, but what it lacks, in order to compete with Linux, is a good text editor. -- \textup{Thomer M. Gil}}
#+END_LaTeX

Today, you begin your journey with Emacs, /the extensible, customizable, self-documenting real-time display editor/.

Because of its complexity, Emacs will seem difficult to grok. Rest assured that learning a select few features and packages more than suffices.

The tinkerer will marvel at the masterpiece which is Emacs. We hack on Emacs because we can; every facet of Emacs is extensible and customizable. Imagine managing email, web browsing, IRC, running shell commands, and compiling code, all just a few keystrokes away. 

Emacs is not for the faint of heart, so buckle up, embrace the challenge and enjoy the ride. I hope to impart a level of Emacs-fu that's sufficient for further self-exploration, and hope you'll enjoy using Emacs as much as I do.

Atom users, go grab yourselves another cup of coffee while you wait for it to load up :P.
#+BEGIN_LaTeX
\begin{flushright}
-- Jethro Kuan
\end{flushright}
#+END_LaTeX

*** 🢒 [[file:introduction.org][Introduction]]                                                  :noexport:
We begin by introducing Emacs, how to get it, and familiarize ourselves with terminology that will appear again and again in later chapters.
